---
title: "Customer Segmentation"
author: "Nihal Neeraj"
execute: 
  echo: false
---


```{r}
#| message: false
#| label: setup

library(tidyverse)
library(tidycensus)
```

```{r}
#| message: false
#| warning: false

plot1 <- read_csv("/Users/neera/OneDrive/Documents/Desktop/projects/Customer_Segmentation/Mall_Customers.csv") |>
  drop_na() |>
  ggplot(aes(x = Gender, y = Age, fill = Gender)) +
  geom_boxplot(width = 0.1) +
  geom_violin(alpha = 0.5,
              width = 0.4) +
  scale_y_continuous(limits = c(10, 70), 
                     breaks = seq(10, 70, by = 10)) +
  theme_minimal() +
  labs(title = "Age Distribution by Gender Among Mall Customers",
       subtitle = "Analysis of Age Variations within Gender Groups",
       x = "Gender",
       y = "Age",
       caption = "Source: Mall Customers Dataset") +
  theme(plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "top",
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10))


print(plot1)
```


```{r}
#| message: false
#| warning: false

plot2 <- read_csv("/Users/neera/OneDrive/Documents/Desktop/projects/Customer_Segmentation/Mall_Customers.csv") |>
  drop_na() |>
  ggplot(aes(x = `Annual Income (k$)`, fill = Gender)) +
  geom_histogram() +
  theme_minimal() +
  labs(
    title = "Distribution of Annual Income by Gender", 
    x = "Annual Income",
    y = " ",
    caption = "Source: Mall Customers Dataset"
  ) +
  scale_x_continuous(
    limits = c(0, 160),
    breaks = seq(0, 160, by = 20)
  ) +
  theme(
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.position = "top",
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12)
  )

print(plot2)
```

